build:
  system_packages:
    - "libssl-dev"
    - "libtesseract-dev"
  python_packages:
    - "accelerate==0.21.0"
    - "bitsandbytes==0.40.2"
    - "boto3==1.28.1"
    - "diffusers==0.18.1"
    - "entrypoints==0.4"
    - "ftfy==6.1.1"
    - "jmespath==1.0.1"
    - "mediapipe==0.10.1"
    - "numpy==1.24.3"
    - "optimum==1.9.1"
    - "pandas==2.0.3"
    - "Pillow==10.0.0"
    - "pydantic==1.10.11"
    - "pytesseract==0.3.10"
    - "python-multipart==0.0.6"
    - "requests==2.31.0"
    - "safetensors==0.3.1"
    - "soundfile==0.12.1"
    - "tensorflow==2.13.0"
    - "torch==2.0.1"
    - "xformers==0.0.20"
    - "gradio==3.37.0"
    - "protobuf==3.20.3"
    - "sentencepiece==0.1.99"
    - "torch==2.0.1"
    - "transformers==4.31.0"
